coverage:
  status:
    project:
      default: false
      main:
        paths:
          - "src/benchmark_environments/"
      tests:
        # Should not have dead code in our tests
        target: 100%
        paths:
          - "tests/"
    patch:
      default: false
      main:
        paths:
          - "src/benchmark_environments/"
      tests:
        target: 100%
        paths:
          - "tests/"
